# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy
#
# config reference: https://github.com/marzer/poxy/wiki/Configuration-options

name            = 'Game Collection'
author          = 'Hendrik Poettker'
description     = 'A collection of game and algorithm implementations'
cpp             = 20
github          = 'hendrik-git/GameCollection'
license         = [ '', '' ]
show_includes   = false
changelog       = 'pages/changelog.md'
#logo            = 'images/banner.png'
#favicon         = 'images/banner.png'
#navbar          = [ 'namespaces', 'annotated' ]
theme           = 'dark'
extra_files     = [
    'images/banner.png',
    #'images/badge-awesome.svg',
    #'images/badge-TOML.svg',
    #'images/badge-gitter.svg',
    #'images/badge-sponsor.svg',
]

[warnings]
enabled         = true
treat_as_errors = false
undocumented    = true

[sources]
paths           = [ 'pages' ]
recursive_paths = [ '../src' ]
patterns        = [ '*.hpp', '*.cpp', '*.dox', '*.md' ]
strip_paths     = [ '../src' ]
extract_all     = true

[images]
paths           = [ 'images' ]

#[badges]
#'C++20'       = [ 'badge-C++20.svg', 'https://en.cppreference.com/w/cpp/compiler_support' ]